Use `.parent_element()` instead of `.parent_node().dyn_into()` (#209)
In a few places, Percy accesses a DOM element's parent by calling `.parent_node()`, then calls `.dyn_into()` on that parent node to cast it to a `web_sys::Element`. `.dyn_into()` checks that a type is an `Element` before performing the cast. For some reason, on Firefox, this type check fails, causing `.dyn_into()` to fail and Percy to panic.

In this PR I replaced everywhere Percy calls `.parent_node().dyn_into()` with a call to `.parent_element()`. This method does the same thing as the old code, but doesn't involve a type check, so it prevents Percy from panicking.

---

I'm not really sure what's causing `.dyn_into()` to fail, so I'm just putting some notes on what I found here. It seems to just be a `web-sys` bug. This is the error I saw in my JS console:

```
panicked at /home/bs/dev/contrib/percy/crates/percy-dom/src/patch/apply_patches.rs:286:53:
called `Result::unwrap()` on an `Err` value: Node { obj: EventTarget { obj: Object { obj: JsValue(HTMLDivElement) } } }
```

...which clearly shows the object Percy tried to cast is an `HTMLDivElement`, which is an `Element`, so casting to it should be fine. I also believe this is a `web-sys` bug because I found the same crash if I called `.dyn_into()` to cast the `Element` returned from `.parent_element()`. In my code for this PR I use this line a few times:

```rs
let parent = node.parent_element().unwrap();
```
If you add a `dyn_into` cast under that like so:
```rs
let parent = node.parent_element().unwrap();
let parent: Element = parent.dyn_into().unwrap();
```

The same panic as before happens. Even though it's casting an `Element` to an `Element` ([`.parent_element()` returns an `Option<Element>`](https://docs.rs/web-sys/latest/web_sys/struct.Node.html#method.parent_element)).